"""Deterministic synthetic corpus and query generator.

The retrieval and migration benchmarks need data with three properties:

1. **Determinism**: a fixed seed produces a byte-identical corpus on
   every run. The plan pins ``MNEME_BENCH_SEED=42`` for this purpose.
2. **Discriminating relevance**: every query has exactly one designated
   answer document, plus a configurable number of *hard negatives* from
   the same topic. nDCG@5 and Recall@10 therefore exercise the
   retriever's ability to break ties between similar documents, not
   just "find any doc on the topic".
3. **Signal vs noise**: each topic has a small fixed vocabulary
   (ten terms). Every document in a topic carries two of those terms in
   its title, deterministically rotated so every term pair is unique
   inside a topic. Queries are built from a target document's title
   pair plus a generic question stem, so the only way to rank the
   target ahead of its same-topic neighbors is to match both terms.

The corpus is intentionally English-only and free of any cultural or
operator-specific vocabulary.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field

# Length-padding suffix so generated queries clear the
# ``RetrievalConfig.min_query_length`` gate (default 20 chars).
_QUERY_STEM = "how does the"
_QUERY_TAIL = "layer behave under load"


@dataclass
class SyntheticDoc:
    """One synthetic markdown document with a known topic label."""

    id: str
    title: str
    body: str
    topic: str
    title_terms: tuple[str, str]


@dataclass
class SyntheticQuery:
    """One synthetic query with the single doc that should rank first.

    ``relevant_doc_ids`` is a list for symmetry with multi-relevant
    retrieval evaluation harnesses, but the generator always populates
    it with exactly one entry.
    """

    qid: str
    text: str
    topic: str
    relevant_doc_ids: list[str] = field(default_factory=list)


@dataclass
class SyntheticCorpus:
    """Full benchmark input: documents, queries, and relevance judgments."""

    docs: list[SyntheticDoc]
    queries: list[SyntheticQuery]
    topics: list[str]


# Generic vocabulary - keeps the bench fixtures free of any
# project-specific or culturally-loaded terms.
_TOPIC_VOCAB: dict[str, list[str]] = {
    "compiler": [
        "compiler", "tokenizer", "parser", "ast", "semantic",
        "lowering", "bytecode", "interpreter", "optimization", "ir",
    ],
    "scheduler": [
        "scheduler", "preempt", "quantum", "thread", "fiber",
        "runqueue", "priority", "cgroup", "deadline", "fairness",
    ],
    "vector_index": [
        "vector", "embedding", "hnsw", "ivf", "quantization",
        "cosine", "annoy", "nlist", "recall", "centroid",
    ],
    "storage_engine": [
        "lsm", "compaction", "memtable", "sstable", "wal",
        "tombstone", "bloomfilter", "compression", "snapshot", "checkpoint",
    ],
    "networking": [
        "tcp", "congestion", "retransmit", "handshake", "throughput",
        "buffer", "socket", "selector", "epoll", "kqueue",
    ],
    "build_system": [
        "incremental", "cache", "manifest", "dependency", "rebuild",
        "fingerprint", "task", "graph", "stamp", "artifact",
    ],
    "type_theory": [
        "covariance", "subtype", "polymorphism", "kind", "monad",
        "functor", "applicative", "trait", "generic", "inference",
    ],
    "garbage_collector": [
        "tracing", "marker", "sweep", "compaction", "generational",
        "barrier", "rootset", "tlab", "reference", "weakref",
    ],
    "consensus": [
        "raft", "paxos", "quorum", "election", "log",
        "leader", "follower", "term", "commit", "snapshot",
    ],
    "rate_limit": [
        "token", "bucket", "leaky", "throttle", "burst",
        "window", "slidewindow", "quota", "backoff", "jitter",
    ],
}

_FILLER = [
    "system", "module", "design", "implementation", "tradeoff",
    "documented", "behavior", "interface", "boundary", "contract",
    "edge", "case", "performance", "regression", "test",
    "fixture", "fast", "slow", "cold", "warm",
    "production", "staging", "rollout", "verify", "measure",
]


def build_synthetic_corpus(
    seed: int = 42,
    docs_per_topic: int = 50,
    queries_per_topic: int = 5,
    body_sentences: int = 6,
) -> SyntheticCorpus:
    """Generate a reproducible corpus and query set.

    Each topic produces ``docs_per_topic`` documents whose title pair
    is generated by rotating two indices over the 10-term topic
    vocabulary; with the default ``docs_per_topic=50`` the pair
    sequence repeats cleanly across the 45 unique unordered pairs plus
    five extras. ``queries_per_topic`` distinct queries are emitted
    per topic, each anchored on a distinct document's title pair.
    """
    rng = random.Random(seed)
    topics = sorted(_TOPIC_VOCAB.keys())

    docs: list[SyntheticDoc] = []
    topic_doc_ids: dict[str, list[str]] = {t: [] for t in topics}
    # Document index by (topic, title_pair) for query targeting.
    by_title_pair: dict[tuple[str, str, str], str] = {}

    for topic in topics:
        vocab = _TOPIC_VOCAB[topic]
        vocab_len = len(vocab)
        for i in range(docs_per_topic):
            doc_id = f"{topic}-{i:03d}"
            topic_doc_ids[topic].append(doc_id)

            # Two terms drawn deterministically so every doc in a topic
            # has a distinct title pair until ``docs_per_topic`` exceeds
            # the number of unique pairs (vocab_len * (vocab_len - 1)).
            a_idx = i % vocab_len
            b_idx = (i // vocab_len + 1 + i) % vocab_len
            if b_idx == a_idx:
                b_idx = (b_idx + 1) % vocab_len
            term_a = vocab[a_idx]
            term_b = vocab[b_idx]
            title = f"Notes on {term_a} {term_b}"
            by_title_pair[(topic, term_a, term_b)] = doc_id

            sentences: list[str] = []
            for _ in range(body_sentences):
                core = rng.choice(vocab)
                filler_terms = rng.sample(_FILLER, k=4)
                sentences.append(
                    f"The {core} layer handles {filler_terms[0]} "
                    f"{filler_terms[1]} with {filler_terms[2]} "
                    f"{filler_terms[3]}."
                )
            body = " ".join(sentences)
            docs.append(
                SyntheticDoc(
                    id=doc_id,
                    title=title,
                    body=body,
                    topic=topic,
                    title_terms=(term_a, term_b),
                )
            )

    queries: list[SyntheticQuery] = []
    for topic in topics:
        # Pick ``queries_per_topic`` documents at evenly spaced indices
        # so the query set covers the topic's docs broadly.
        chosen_indices: list[int] = []
        if docs_per_topic > 0:
            step = max(1, docs_per_topic // max(1, queries_per_topic))
            for j in range(queries_per_topic):
                chosen_indices.append((j * step) % docs_per_topic)
        for j, doc_idx in enumerate(chosen_indices):
            doc = next(d for d in docs if d.id == f"{topic}-{doc_idx:03d}")
            term_a, term_b = doc.title_terms
            text = f"{_QUERY_STEM} {term_a} {term_b} {_QUERY_TAIL}"
            queries.append(
                SyntheticQuery(
                    qid=f"{topic}-q{j:02d}",
                    text=text,
                    topic=topic,
                    relevant_doc_ids=[doc.id],
                )
            )

    return SyntheticCorpus(docs=docs, queries=queries, topics=topics)
