/**
 * mneme_propose — queue writer for the policy drain.
 *
 * Covers: record shape parity with the Python queue_proposal format,
 * cross-language uuid5 identity, redaction-before-queue (C4), path
 * containment, and auto-eligibility reporting against policy.json.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { proposeTool, ProposeInputSchema } from "../src/tools/propose.js";
import { makeTempVault } from "./helpers/vault_fixture.js";

function readQueue(rootDir: string): Array<Record<string, unknown>> {
	const queuePath = join(rootDir, ".mneme", "proposals", "pending.jsonl");
	if (!existsSync(queuePath)) return [];
	return readFileSync(queuePath, "utf-8")
		.split("\n")
		.filter((l) => l.trim().length > 0)
		.map((l) => JSON.parse(l) as Record<string, unknown>);
}

describe("mneme_propose", () => {
	it("queues a redacted record in the Python drain format", () => {
		const { vault, rootDir } = makeTempVault("propose");
		const result = proposeTool(
			{
				action: "create",
				path: "notes/parity.md",
				content: "hello <private>secret</private> world",
				category: "ephemeral",
				edit_class: undefined,
			},
			vault,
		);
		expect(result.ok).toBe(true);
		if (!result.ok) return;
		expect(result.data.redactions_applied).toBe(1);

		const records = readQueue(rootDir);
		expect(records).toHaveLength(1);
		const rec = records[0] as Record<string, unknown>;
		expect(rec.action).toBe("create");
		expect(rec.target_path).toBe("notes/parity.md");
		expect(rec.content).toBe("hello [REDACTED] world");
		expect(rec.category).toBe("EPHEMERAL");
		expect(rec.status).toBe("PENDING");
		expect(rec.trust).toBe("agent");
		expect(rec.edit_class).toBeNull();
		expect(rec.scope).toBe("default");
		expect(result.data.scope).toBe("default");
	});

	it("derives the same uuid5 proposal_id as the Python engine", () => {
		// Fixture generated by mneme_core.approval.propose for the same
		// action/path/content/category/trust tuple.
		const { vault } = makeTempVault("propose-id");
		const result = proposeTool(
			{
				action: "create",
				path: "notes/parity.md",
				content: "hello <private>secret</private> world",
				category: "ephemeral",
				edit_class: undefined,
			},
			vault,
		);
		expect(result.ok).toBe(true);
		if (!result.ok) return;
		expect(result.data.proposal_id).toBe(
			"6b3b75e0-c5ac-5916-a299-faa94d74a8d2",
		);
	});

	it("uses scope in non-default proposal identity while preserving default IDs", () => {
		const { vault } = makeTempVault("propose-scoped-id");
		const alpha = proposeTool(
			ProposeInputSchema.parse({
				action: "create",
				path: "notes/parity.md",
				content: "same",
				scope: "alpha",
			}),
			vault,
		);
		const beta = proposeTool(
			ProposeInputSchema.parse({
				action: "create",
				path: "notes/parity.md",
				content: "same",
				scope: "beta",
			}),
			vault,
		);
		expect(alpha.ok && alpha.data.scope).toBe("alpha");
		expect(beta.ok && beta.data.scope).toBe("beta");
		expect(alpha.ok && beta.ok && alpha.data.proposal_id).not.toBe(
			beta.ok ? beta.data.proposal_id : "",
		);
	});

	it("rejects wildcard durable scope in the public schema", () => {
		expect(
			ProposeInputSchema.safeParse({
				action: "create",
				path: "notes/x.md",
				scope: "*",
			}).success,
		).toBe(false);
	});

	it("refuses a path that escapes the vault", () => {
		const { vault } = makeTempVault("propose-escape");
		const result = proposeTool(
			{
				action: "create",
				path: "../outside.md",
				content: "escape",
				category: "ephemeral",
				edit_class: undefined,
			},
			vault,
		);
		expect(result.ok).toBe(false);
		if (result.ok) return;
		expect(result.error.code).toBe("PATH_OUTSIDE_VAULT");
	});

	it("reports auto-eligibility from policy.json", () => {
		const { vault, rootDir } = makeTempVault("propose-policy");
		writeFileSync(
			join(rootDir, ".mneme", "policy.json"),
			JSON.stringify({ auto_approve: ["typo-fix"] }),
			"utf-8",
		);
		const eligible = proposeTool(
			{
				action: "update",
				path: "notes/a.md",
				content: "fix",
				category: "ephemeral",
				edit_class: "typo-fix",
			},
			vault,
		);
		const held = proposeTool(
			{
				action: "update",
				path: "notes/b.md",
				content: "merge",
				category: "ephemeral",
				edit_class: "dedup-merge",
			},
			vault,
		);
		expect(eligible.ok && eligible.data.auto_eligible).toBe(true);
		expect(held.ok && held.data.auto_eligible).toBe(false);
	});

	it("durable categories are never auto-eligible", () => {
		const { vault, rootDir } = makeTempVault("propose-durable");
		writeFileSync(
			join(rootDir, ".mneme", "policy.json"),
			JSON.stringify({ auto_approve: ["typo-fix"] }),
			"utf-8",
		);
		const result = proposeTool(
			{
				action: "update",
				path: "identity/me.md",
				content: "new identity",
				category: "identity",
				edit_class: "typo-fix",
			},
			vault,
		);
		expect(result.ok).toBe(true);
		if (!result.ok) return;
		expect(result.data.auto_eligible).toBe(false);
	});
});
