"""Deterministic Markdown report generator for mneme-graph (R6 / TASK B4).

Public API
----------
generate_report(store)         -> str   Markdown GRAPH_REPORT from a GraphStore.
write_report(vault_path, out)           Load graph and write .md to *out*.

Privacy: the report contains only identifiers / vault-relative paths / counts
-- no file content is included.

Determinism: sorted sections ensure byte-identical output for identical
graph.json input.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from .schema import GraphEdge, GraphNode
from .store import GraphStore

# Node kinds that are counted in the noise summary.
# Headings are structurally inflated and not semantically authored nodes.
_NOISE_KINDS: frozenset[str] = frozenset({"heading"})


def generate_report(store: GraphStore) -> str:
    """Return a deterministic Markdown GRAPH_REPORT string.

    Sections (in order):
      - Summary        -- total node and edge counts
      - Node Counts by Kind  -- one row per kind, alphabetical
      - Edge Counts by Kind  -- one row per kind, alphabetical
      - Top-Referenced Notes -- by in-degree (computed directly from edges)
      - Tags                 -- sorted list of tag node names
      - Noise Summary        -- structurally-inflated node kinds (headings)
      - Determinism          -- prose note about sort order

    In-degree is computed directly from edges; analytics is not imported so
    this module stays decoupled from parallel edits to analytics.py.

    Privacy: only identifiers, vault-relative paths, and counts are emitted.
    No file content appears in the output.
    """
    nodes: list[GraphNode] = store.nodes
    edges: list[GraphEdge] = store.edges

    total_nodes: int = len(nodes)
    total_edges: int = len(edges)

    node_counts: Counter[str] = Counter(n.kind for n in nodes)
    edge_counts: Counter[str] = Counter(e.kind for e in edges)

    # In-degree: number of edges arriving at each node_id.
    # Computed directly from edges -- no analytics dependency.
    in_degree: Counter[str] = Counter(e.dst_id for e in edges)

    node_by_id: dict[str, GraphNode] = {n.node_id: n for n in nodes}

    # Top-referenced notes (kind == "note") by in-degree.
    # Secondary sort key is source_path for full determinism on ties.
    note_pairs: list[tuple[str, int]] = [
        (node_by_id[nid].source_path, cnt)
        for nid, cnt in in_degree.most_common()
        if nid in node_by_id and node_by_id[nid].kind == "note"
    ]
    note_pairs.sort(key=lambda x: (-x[1], x[0]))
    top_notes = note_pairs[:10]

    # Tags: sorted list of unique tag node names.
    tags: list[str] = sorted({n.name for n in nodes if n.kind == "tag"})

    # Noise: structurally-inflated node kinds present in the graph.
    noise: dict[str, int] = {
        k: node_counts[k] for k in sorted(node_counts) if k in _NOISE_KINDS
    }

    # ------------------------------------------------------------------ #
    # Build the Markdown document line by line.                           #
    # ------------------------------------------------------------------ #
    lines: list[str] = []

    lines += ["# GRAPH_REPORT", ""]
    lines += [
        "<!-- Generated by mneme-graph report.py. Do not edit manually. -->",
        "",
    ]

    # --- Summary ---
    lines += ["## Summary", ""]
    lines += [
        "| Metric | Count |",
        "|--------|-------|",
        f"| Total nodes | {total_nodes} |",
        f"| Total edges | {total_edges} |",
        "",
    ]

    # --- Node Counts by Kind ---
    lines += ["## Node Counts by Kind", ""]
    if node_counts:
        lines += ["| Kind | Count |", "|------|-------|"]
        for kind in sorted(node_counts):
            lines.append(f"| {kind} | {node_counts[kind]} |")
    else:
        lines.append("_No nodes found._")
    lines.append("")

    # --- Edge Counts by Kind ---
    lines += ["## Edge Counts by Kind", ""]
    if edge_counts:
        lines += ["| Kind | Count |", "|------|-------|"]
        for kind in sorted(edge_counts):
            lines.append(f"| {kind} | {edge_counts[kind]} |")
    else:
        lines.append("_No edges found._")
    lines.append("")

    # --- Top-Referenced Notes ---
    lines += ["## Top-Referenced Notes (by In-Degree)", ""]
    if top_notes:
        lines += [
            "| Note (vault-relative path) | In-Degree |",
            "|----------------------------|-----------|",
        ]
        for path, deg in top_notes:
            lines.append(f"| {path} | {deg} |")
    else:
        lines.append("_No note nodes found or no notes are referenced._")
    lines.append("")

    # --- Tags ---
    lines += ["## Tags", ""]
    if tags:
        for tag in tags:
            lines.append(f"- `{tag}`")
    else:
        lines.append("_No tags found._")
    lines.append("")

    # --- Noise Summary ---
    lines += ["## Noise Summary", ""]
    if noise:
        lines += ["| Kind | Count |", "|------|-------|"]
        for kind, cnt in noise.items():
            lines.append(f"| {kind} | {cnt} |")
    else:
        lines.append("_No noise nodes detected._")
    lines.append("")

    # --- Determinism note ---
    lines += [
        "## Determinism",
        "",
        (
            "All sections are sorted deterministically: node/edge tables by kind "
            "(alphabetical), top notes by descending in-degree then vault-relative "
            "path, tags alphabetically. "
            "Re-running on the same graph.json produces byte-identical output."
        ),
        "",
    ]

    return "\n".join(lines)


def write_report(vault_path: Path, out_path: Path) -> None:
    """Load graph from *vault_path* and write GRAPH_REPORT.md to *out_path*.

    Args:
        vault_path: vault root directory; must contain .mneme/graph.json.
        out_path:   destination .md file; parent directory must already exist.
    """
    store = GraphStore.load(vault_path)
    content = generate_report(store)
    out_path.write_text(content, encoding="utf-8")
